version: "3.8"

services:
  frontend:
    container_name: laravel_8010
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:80"
    volumes:
      - .:/var/www/html
    networks:
      - examen-red 

networks:
  examen-red:
    external: true
